// Real client logos, supplied directly by the client and stored in public/clients.
// `name` is used only for alt text; most are inferred from the source filename.
export const clientLogos = [
  { file: "active-planet.jpg", name: "Active Planet" },
  { file: "ad-house.png", name: "Ad House" },
  { file: "adcaster.png", name: "Adcaster" },
  { file: "aifer.jpg", name: "Aifer" },
  { file: "alhid.png", name: "Alhid" },
  { file: "ashcorp.webp", name: "Ashcorp" },
  { file: "atomic-systems.png", name: "Atomic Systems" },
  { file: "banca.jpg", name: "Banca" },
  { file: "berry-n-co-cafe.jpg", name: "Berry N Co Cafe" },
  { file: "bexfolio-edu.jpg", name: "Bexfolio Edu" },
  { file: "catalyst.png", name: "Catalyst" },
  { file: "chankya-business-school.png", name: "Chankya Business School" },
  { file: "de-beacon.jpg", name: "De Beacon" },
  { file: "eagles.jpg", name: "Eagles" },
  { file: "edex.png", name: "Edex" },
  { file: "edubird.png", name: "Edubird" },
  { file: "edusolve.png", name: "Edusolve" },
  { file: "elance.jpg", name: "Elance" },
  { file: "endesa.png", name: "Endesa" },
  { file: "entryline.png", name: "Entryline" },
  { file: "etern-learning.png", name: "Etern Learning" },
  { file: "evoka.png", name: "Evoka" },
  { file: "exintra-builders.png", name: "Exintra Builders" },
  { file: "finjet-loan-logo.png", name: "Finjet Loan Logo" },
  { file: "freshstory.png", name: "Freshstory" },
  { file: "g-stock.jpg", name: "G Stock" },
  { file: "gedexo.jpg", name: "Gedexo" },
  { file: "gezpacho-kitches.jpg", name: "Gezpacho Kitches" },
  { file: "guly-interiors.jpg", name: "Guly Interiors" },
  { file: "gypsy-circle.jpg", name: "Gypsy Circle" },
  { file: "hindiplus.png", name: "Hindiplus" },
  { file: "i-learn.png", name: "I Learn" },
  { file: "iamt.png", name: "Iamt" },
  { file: "imax.png", name: "Imax" },
  { file: "interval.jpg", name: "Interval" },
  { file: "itees-eye-hospital.png", name: "Itees Eye Hospital" },
  { file: "jrs.png", name: "Jrs" },
  { file: "kairali-trails.jpg", name: "Kairali Trails" },
  { file: "maddyverse.jpg", name: "Maddyverse" },
  { file: "mailbox.png", name: "Mailbox" },
  { file: "marque-way.jpg", name: "Marque Way" },
  { file: "mf-aqua.png", name: "Mf Aqua" },
  { file: "mindview.jpg", name: "Mindview" },
  { file: "my-bathrooms-by-tps.webp", name: "My Bathrooms By Tps" },
  { file: "nesta.png", name: "Nesta" },
  { file: "nexora.jpg", name: "Nexora" },
  { file: "nurture-crm.png", name: "Nurture Crm" },
  { file: "odox.jpg", name: "Odox" },
  { file: "pay-n-back.jpg", name: "Pay N Back" },
  { file: "persian-pastries.jpg", name: "Persian Pastries" },
  { file: "pk-stories.jpg", name: "Pk Stories" },
  { file: "planvacations.png", name: "Planvacations" },
  { file: "platinum-academy.jpg", name: "Platinum Academy" },
  { file: "prodigy.jpg", name: "Prodigy" },
  { file: "proskill.jpg", name: "Proskill" },
  { file: "rac.jpg", name: "Rac" },
  { file: "rays-education.png", name: "Rays Education" },
  { file: "roofs-and-shades.jpg", name: "Roofs And Shades" },
  { file: "royal-assests.png", name: "Royal Assests" },
  { file: "royal-gold.png", name: "Royal Gold Algo" },
  { file: "royal-grad.jpg", name: "Royal Grad" },
  { file: "shelter-arms.png", name: "Shelter Arms" },
  { file: "skill-mount.jpg", name: "Skill Mount" },
  { file: "sky-builders.jpg", name: "Sky Builders" },
  { file: "smart.png", name: "Smart" },
  { file: "solus.png", name: "Solus" },
  { file: "squareyards.png", name: "Squareyards" },
  { file: "standmark.jpg", name: "Standmark" },
  { file: "sunny-day.jpg", name: "Sunny Day Solar" },
  { file: "techoriz.jpg", name: "Techoriz" },
  { file: "texttutor.png", name: "Texttutor" },
  { file: "thycha.png", name: "Thycha" },
  { file: "timson-lightings.png", name: "Timson Lightings" },
  { file: "tuitonline.png", name: "Tuitonline" },
  { file: "v-trust-eye-hospital.jpg", name: "V Trust Eye Hospital" },
  { file: "vona-school-of-design.svg", name: "Vona School Of Design" },
  { file: "wydex.jpg", name: "Wydex" },
  { file: "xbyte-tera.png", name: "Xbyte Tera" },
  { file: "yeloria.png", name: "Yeloria" },
] as const;
